[project]
name = "korean_glue"
version = "0.1.0"
description = "A modern Python library for Korean josa processing with dictionary support and framework integrations."
readme = "README.md"
license = { file = "LICENSE" }
authors = [ { name = "Codex", email = "codex@openai.com" } ]
requires-python = ">=3.8"
dependencies = []

[project.optional-dependencies]
django = []
jinja = ["Jinja2>=3.0"]
dev = ["pytest", "pytest-cov", "black", "flake8", "mypy", "pre-commit"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["tests"]
