
name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
          activate-environment: true
          enable-cache: true
      - name: Build wheel
        run: uv build
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
